language: python
dist: xenial
sudo: false
python:
  - "3.7"
  - "3.6"
  - "3.5"

addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgresql-9.5-postgis-2.4
    - binutils
    - libproj-dev
    - python3-gdal
    - libgeos-dev
    - libyaml-dev
    - libgnutls28-dev

install:
  - "pip install coveralls"
  - "pip install -r requirements/test.txt"

before_script:
  - psql -c 'create database osmcha;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d osmcha
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d osmcha

script:
- coverage run manage.py test --settings=config.settings.tests

after_success:
  - coveralls

notifications:
  email: false
